### ISSUE TITLE
 Overhang detection disabled in PrusaSlicer.

### ISSUE THREAD

**Issue by mehmetpakkabaggen** [nicolai-wachenschwan/arc-overhang-prusaslicer-integration#18]
Hi, when i try to export  get error that i dont htve  Overhang detection in PrusaSlicer. i cant find any settings for that neither online or in the app itself.
here is the full error message:
C:\temp\prusa_slicer_post_processing_script.py:1080: Overhang detection disabled in PrusaSlicer. Activate in PrusaSlicer for script success!
C:\temp\prusa_slicer_post_processing_script.py:111: Incompatible PursaSlicer-Settings used!
Can not run script, gcode unmodified. Press enter to close.

**Comment by nicolai-wachenschwan** [comment]
It is here, you need to set your expirience to advanced or expert (top right corner) to see this.

![BridgeSetting](https://user-images.githubusercontent.com/38214064/226204776-22723d2f-03e4-4383-a587-5cf5d7789fcc.png)
This is german text, but the position will be the same for all languages.

**Comment by jdf221** [comment]
It's called "Detect bridging perimeters" in the English version seemingly:

<img width="298" alt="image" src="https://user-images.githubusercontent.com/6322057/226232810-47507c8e-60ca-47d1-a9f4-aa540002cb5c.png">

**Comment by nicolai-wachenschwan** [comment]
Perfect, thank you for your help! I clarified the warning with matching text.
