### ISSUE TITLE
Script won't run in prusaslicer postprocessing

### ISSUE THREAD

**Issue by iterhating** [nicolai-wachenschwan/arc-overhang-prusaslicer-integration#2]
Thanks for the quick response time. I updated to 2.5.0 (hadn't realized this computer was lagging) and that previous gcode issue is sorted, but a new one arose which **required** the activation of "Detect Bridging Perimeters" before the code would run. I don't see this anywhere in the readme so I'm not sure if it's papering over another error or was just always required and not made explicit.

Upshot of it is, the script now works when run in terminal, and I confirmed the printing path is correct in gcode viewer. However, it won't run when called by prusaslicer, and the error message is 

Failed starting the script 
C:\Users\iterhating\Documents\Octolab\FDM\arc-overhang-prusaslicer-integration\prusa_slicer_post_processing_script.py C:\Users\iterhating\AppData\Local\Temp\.17896.gcode.pp, Win32 error: 193

Any suggestions?

**Comment by osvobo** [comment]
Hi, did you add both paths in your postprocessing output options? I was getting the same error when my python wasn't correctly defined. 
Here are my settings:
![image](https://user-images.githubusercontent.com/68607250/222556779-ddabb475-48c3-4e49-9443-c1f562250c46.png)

**Comment by iterhating** [comment]
And here I just wasn't following the instructions, thanks! That fixed it.
