### ISSUE TITLE
"can not run script, gcode unmodified" error

### ISSUE THREAD

**Issue by danwiley** [nicolai-wachenschwan/arc-overhang-prusaslicer-integration#21]
trying to run the script on ender 3 v2 profile but im getting this error - "can not run script, gcode unmodified". i have noticed that when i change my profile to one of prusa printers the scripts run just fine. how can i fix this issue with my profile? or an update on the script will make creality compatible too? im so excited with this project and cant wait to try it!

**Comment by nicolai-wachenschwan** [comment]
Probably PrusaSlicer Setting, please copy the Full printout from the Script and Paste it here.

**Comment by danwiley** [comment]
Im sorry, printout?

**Comment by nicolai-wachenschwan** [comment]
The Script opens a new window. Usually a Black one. It writes text there. I need you to copy that Text and paste it here.

**Comment by danwiley** [comment]
![image](https://user-images.githubusercontent.com/128372173/226407419-30a9c89b-ede7-4e7f-b5b7-e1572031b3fd.png)
it wont let me copy so i sent a screenshot. hops it helps

**Comment by danwiley** [comment]
well i kinda feel stupid here because after having a second look, the problem was obvious. had to turn on detect bridging perimeters ;)
