### ISSUE TITLE
TypeError: '<' not supported between instances of 'str' and 'float'

### ISSUE THREAD

**Issue by lkera** [nicolai-wachenschwan/arc-overhang-prusaslicer-integration#23]
line 1076, in checkforNecesarrySettings
    if gCodeSettingDict.get("extrusion_width")<0.001 or gCodeSettingDict.get("perimeter_extrusion_width")<0.001 or gCodeSettingDict.get("solid_infill_extrusion_width")<0.001:

**Comment by lkera** [comment]
any idea as to the cause of this error ?

**Comment by maruhe** [comment]
did you check if you find this settings at the end of your gcode? (check extrusion_width, perimeter_extrusion_width and solid_infill_extrusion_width)

**Comment by nicolai-wachenschwan** [comment]
exactly, you need to set a numeric value for your extrusionwidths. Else this error will occur.
