### ISSUE TITLE
hilbert surface gets printed again on top surface

### ISSUE THREAD

**Issue by maruhe** [nicolai-wachenschwan/arc-overhang-prusaslicer-integration#24]
attached the models I created to test ArcOverhangs

may it's because the thickness of the overhang is quite low
I reduced BottomLayers to 3 and after ArcOverhangs and hilbert surface the infill starts (even printing slow)
but after the infill it starts again with hilbert surface printing super slow and this destried the prints (I think because the hot nozzle was nearby / touching the overhang-area for long time

I'm printing ABS and the ArcOverhangs work great!
just the following layers need to get printed faster
is there an option to limit the number of hilbert layers and the number of slow layers?

[arc.zip](https://github.com/nicolai-wachenschwan/arc-overhang-prusaslicer-integration/files/11035850/arc.zip)

while testing I also saw some moves in the infill above the hilbert that have been ultra slow and creating little blobs on the outer surface
I didn't found that part in the gcode but it felt like a G1 command without feedrate using an old slow feedrate

**Comment by nicolai-wachenschwan** [comment]
Yes, there are 2 parameters defined to this usecase. You need to adapt the parameters in the "parameter" section of the script according to your needs.
Navigate to Special Cooling Settings. There you find specialCoolingZdist, which is the Z distance the special cooling settings are applied and therefore every solid infill within beeing convertet to hilbert. Default is 3mm, but you can lower it to exclude the top surfaces.

PrintSpeed:
change "aboveArcsPerimeterPrintSpeed" and "aboveArcsInfillPrintSpeed" to modify the printing speeds according to your needs.

**Comment by maruhe** [comment]
specialCoolingZdist is a nice hint, before it looked like this 
in case I will fix something I_ll create a pull request :-)
![grafik](https://user-images.githubusercontent.com/49123648/227644704-c581aac6-45a6-4c1d-ae6b-d8aaf992941e.png)

i still get this ultra-slow line but din't found it yet but I found a missing linebreak
![grafik](https://user-images.githubusercontent.com/49123648/227645169-240753e3-a518-45cf-b63a-d90f06e14096.png)
also saw missing linebreaks in other files before:
![grafik](https://user-images.githubusercontent.com/49123648/227645365-f015e51e-c1a2-47fd-bfc1-d27d7d0f0b5c.png)

**Comment by billfj4045** [comment]
I presume that these changes are in the .py script itself and not in Prusa Slicer. That might be a step out of my league, but will make a copy of the original script and see what I can do to make those adjustments. Fingers crossed!
