### ISSUE TITLE
Error with script on mac

### ISSUE THREAD

**Issue by bifaciall** [nicolai-wachenschwan/arc-overhang-prusaslicer-integration#27]
![image](https://user-images.githubusercontent.com/83917104/227000072-9c949b25-9915-4bc0-b7c2-39580d1df445.png)
it says it doesnt have permission how to fix?

**Comment by 5axes** [comment]
You must give also the path to the Python Exe not only the path of the script.

**Comment by bifaciall** [comment]
nvm works now but now it says that there is no such module shapely although I installed it
