### ISSUE TITLE
Problem with modules on mac

### ISSUE THREAD

**Issue by bifaciall** [nicolai-wachenschwan/arc-overhang-prusaslicer-integration#28]
when I try to run it, it says there is no module named shapely-> ergo i hadnt installed it; thing is: I have

**Comment by nicolai-wachenschwan** [comment]
probably you have multiple python executables. (Kind of usual).
Fix: open terminal and insert the complete path of the python-executable, just as the first path in the prusaSlicer script.
 Than append the mac-command for pip install shapely and press enter.
 =>will install the lib in the right python environment.
 
 Please try this and report if it was successful :)

**Comment by salamanders** [comment]
I was able to get it to execute on a mac with default python pip install steps.   +1 to "you may have installed the dependencies in a different place"

**Comment by Henk72** [comment]
Thanks for the answer, great solution

**Comment by bifaciall** [comment]
> probably you have multiple python executables. (Kind of usual).
> 
> Fix: open terminal and insert the complete path of the python-executable, just as the first path in the prusaSlicer script.
> 
>  Than append the mac-command for pip install shapely and press enter.
> 
>  =>will install the lib in the right python environment.
> 
>  
> 
>  Please try this and report if it was successful :)

I will try it when im home
