### ISSUE TITLE
Got it to run, but may not be handing it the "right" gcode to show off the capabilities.

### ISSUE THREAD

**Issue by salamanders** [nicolai-wachenschwan/arc-overhang-prusaslicer-integration#32]
This isn't a bug, more of a question of "am I feeding this script the right starting point?"

I openSCAD rendered a complex organic dragon-egg looking thing with lots of small scale overhang areas.  Cool.  Then I 

1. plop it into PrusaSlicer, 
2. turn on the necessary bridge detection settings,
3. Set the infill to 0% because I'd like this to be as close to vase-mode as possible
4. Set the layer height down from the suggested 0.3 (I'm using a 0.6 nozzle) down to 0.1 because it helps draw more layers on the steeply slanting areas 
5. Hope it can handle the steeply-sloping but not-quite-horizontal planes
6. run it through this script.   Script runs without complaints
7. But I don't see the scallop-like patterns 

Step num 3, 4, 5 all could be me doing it wrong.
I... don't think I did it right.  The overhangish areas are still back-and-forth squiggles not growing-arc shell-like patterns.

**Comment by nicolai-wachenschwan** [comment]
1) window in PrusaSlicer wont change. Open file sperately.
2)Parameters: min Overhang area might be to small=>not generating arcs in these areas. Change parameter if needed.
