### ISSUE TITLE
Extrusion generated between disconnected bodies

### ISSUE THREAD

**Issue by Qmodo** [nicolai-wachenschwan/arc-overhang-prusaslicer-integration#33]
I tried running the script on a file containing two disconnected bodies, and it generated a number of extrusions between the two. They generated only on layers that were modified by the script.

![image](https://user-images.githubusercontent.com/18293675/227805595-36db2073-d08d-452d-84fc-5fcf3abb9ed8.png)

The layers that feature it are the arc overhangs, then the Hilbert curve infill, none appear on the layers with gyroid infill as selected in PrusaSlicer, then it appears again on the layers of Hilbert before the top layer. 

I haven't attempted printing it, but in PrusaSlicer G-code Viewer, it shows them listed perimeters, except one that is listed as internal infill. I am somewhat curious if these may just be travel moves that are improperly listed by the viewer.

[My files (gcode, and 3mf with the printer/profiles](https://github.com/nicolai-wachenschwan/arc-overhang-prusaslicer-integration/files/11073122/Adapter.Files.zip)

I'm seeing now that there's some similar issues mentioned in Thomas Sandlander's video, as well as the 8th limitation listed on the main project page, so if this is the same thing, please go ahead and close it! I figured I should mention it anyway since I haven't seen anything about multi body files

Computer Info:
OS: Windows 11 (build 22621), 64-bit edition
Version: PrusaSlicer-2.6.0-alpha5+win64-202303061442
Python: Python-3.11.2-amd64

**Comment by nicolai-wachenschwan** [comment]
Yes, it is that bug. I did not find the Time to fix it yet.
