### ISSUE TITLE
Post-processing script Error

### ISSUE THREAD

**Issue by EduardoMDSousa** [nicolai-wachenschwan/arc-overhang-prusaslicer-integration#40]
Good afternoon, I am not able to understand the reason for this error,
I use another script accelerations.py, this one works fine, but when I try to use prusa_slicer_post_processing_script.py, I always get the error below.
I already tested with pyton 3.10 and 3.11
all libraries are installed

thanks

Post-processing script 
C:\python-3.10.0\scripts\prusa_slicer_post_processing_script.py 
on file C:\Users\Eduardo\AppData\Local\Temp\.4904.gcode.pp failed.
Error code: 1

**Comment by EduardoMDSousa** [comment]
Post-processing script C:\Users\Eduardo\AppData\Local\Programs\Python\Python310\python.exe C:\python-3.10.0\scripts\prusa_slicer_post_processing_script.py on file C:\Users\Eduardo\AppData\Local\Temp\.7432.gcode.pp failed.
Error code: 1

**Comment by amatulic** [comment]
You get better diagnostic information if you run the script from the commandline. I encountered a TypeError and filed issue #42. It may be the same as what you encountered, but there's no way to know unless you run it from the commandline.

**Comment by nicolai-wachenschwan** [comment]
When executing the script there opens a new window with detailed informaion. If it closes to quick try running it from the commandline.
