### ISSUE TITLE
Printer nocks print off buildplate

### ISSUE THREAD

**Issue by 1Euro7Cent** [nicolai-wachenschwan/arc-overhang-prusaslicer-integration#48]
I've ran the script and it works fine. In the print when it generates the first few arcs it always goes back to starting pos of the next arc at the same pos. At the start of every arc a small blob appears and at that move it crashed into the print.

You can see the blobs I was talking about
![20230501_195944](https://user-images.githubusercontent.com/67194495/235502556-fe231ada-9535-4577-b416-477c05043c8e.jpg)

![20230501_195950](https://user-images.githubusercontent.com/67194495/235502619-cdd6a353-a851-4448-a6a3-3dd8fe36d207.jpg)

**Comment by 1Euro7Cent** [comment]
A possibility to fix that is by adding a "zHop" like system or plan the travel moves outside of already printed paths.

Or fix the blob stuff

**Comment by nicolai-wachenschwan** [comment]
Just did a quick fix in the lunch break, now fixed for real. at least it works on my machine :)

**Comment by 1Euro7Cent** [comment]
I think you messed up some units. It is printing now and it retracts. But it retracts like 100X slower than I've set it to(I've set it to 30 mm/s)
![image](https://user-images.githubusercontent.com/67194495/236285246-bbd34c4b-a71d-4846-a899-a77d54ed9cba.png)

**Comment by 1Euro7Cent** [comment]
It should take less than a second. But it takes like 3 seconds(0.8 mm retract)

**Comment by nicolai-wachenschwan** [comment]
Jup. Fixed….

**Comment by 1Euro7Cent** [comment]
The blob issue is fixed but the part bend because of that wiered layer above it. (it softened the arcs)
![20230504_200716](https://user-images.githubusercontent.com/67194495/236291488-e3638c8b-8b30-4a4a-b468-198b96f3ef0d.jpg)

**Comment by nicolai-wachenschwan** [comment]
Perfect! Just Use a little more cooling in the special cooling settings and experiment a bit with the paramesters:)

**Comment by 1Euro7Cent** [comment]
Ok. That fixes my problems. Going to find some time tuning value.
