### ISSUE TITLE
Solid infill above overhang is not rectilinear

### ISSUE THREAD

**Issue by lwhist** [nicolai-wachenschwan/arc-overhang-prusaslicer-integration#49]
When looking at the printer during the printing of the layers above the overhang (only solid infill), it looks like a labyrinth and is not rectilinear as it usually is. I cannot find a way to correct this.

Do you have any suggestions on how to fix this?

Kind regards, 
Lars

**Comment by nicolai-wachenschwan** [comment]
Yes, this is on purpose to avoid warping. The Parameter „specialCoolingZdist“ =0 will deactivate this.
