### ISSUE TITLE
Python 3.5 compatibility issue by type hints

### ISSUE THREAD

**Issue by 18Markus1984** [nicolai-wachenschwan/arc-overhang-prusaslicer-integration#5]
Hello. I now tried both methods and both doesn't work for me. I have a Windows 11 x64 system. I didn't change the code, maybe there is something that I'm missing. I would be really happy to find a solution. Likewise, I want to try to integrate the arc-support in my workflow. I'm working in a makerspace and the arc overhangs could be a way to drastically reduce the waste material.

**Methode A:**
![Screenshot 2023-03-03 161107](https://user-images.githubusercontent.com/52409213/222756681-a8ac5c38-4962-4fb3-9ee7-c107dbde7e6b.png)
**Methode B:**
![Screenshot 2023-03-03 160850](https://user-images.githubusercontent.com/52409213/222756691-34eeba3e-fd7d-47b0-8f40-8aa7ad9cf2c6.png)
My PrusaSlicer integration
![grafik](https://user-images.githubusercontent.com/52409213/222757616-6fe44584-cd26-45e4-82c9-2f05b96b3aec.png)

**Comment by 18Markus1984** [comment]
Yes tried it but somehow after installing the newest version of python 3.11.2 it doesn't get the correct link to the new version and I really don't know how to fix this. I'm sorry for being so helpless. I'm not really into the windows terminal. I more like the linux console. 
![grafik](https://user-images.githubusercontent.com/52409213/222903819-709499d5-489b-4790-8c44-4f893750ee50.png)

**Comment by nicolai-wachenschwan** [comment]
Hey Markus,
The Problem is with the „type hints“. You can delete those, Since they are not needed, but for debugging. Just delete „ | None“ (Same for the Otter occurences) and it should work. 
will update the Code next week as a permanent fix.

**Comment by 18Markus1984** [comment]
I'm feeling so stupid right now. Sorry bothering you again. I removed the | None with search and exchange. But sadly I still got this two errors in Line 353 and 415.

![grafik](https://user-images.githubusercontent.com/52409213/222923784-210dca52-b1d3-4277-8d40-30fa3dc81c0d.png)

**Comment by nicolai-wachenschwan** [comment]
No Problem, modifying Code is not an obvious solution :)
You can delete everything between „->“ and „:“ including „->“ in the lines that causes errors, until it works or gives a different error. The line Thema should end with „):“ The error are just type hints, they are not needed for the execution of the Code. I will Fix and Update the Code next week to avoid the Problem for future users:)

**Comment by nicolai-wachenschwan** [comment]
Hey Markus,
Firstly: Thank you for submitting the Issue, so the code can be truely compatible to the specs in the readme :)

I removed the trouble causing type hints. It would be perfect, if you could test the updated code in your usual Python env!
I added some new functionality to reduce warping, so please make sure you also pip install "numpy-hilbert-curve" :P

@wetwool : thank you for pointing that out, since I work in Python 3.10 I totally missed that issue!

**Comment by 18Markus1984** [comment]
I used the new script and installed numpy-hilbert curve and used 3.8, but it doesn't work 
![grafik](https://user-images.githubusercontent.com/52409213/223371413-a9bdde22-8af8-4736-8aff-01752e26632b.png)

**Comment by 18Markus1984** [comment]
I worked I installed Python 3.10. Only thing you should add is to use "<PATH-TO-FILE>" between paths that have " "
![grafik](https://user-images.githubusercontent.com/52409213/223462439-86ab3c23-56c5-4a82-a0b8-27f0057a74ac.png)

The only was a little bit overextrusion add the overhang spot:
![grafik](https://user-images.githubusercontent.com/52409213/223462161-ae6374fb-1f5a-4a70-ba92-dd5603e037a4.png)
![grafik](https://user-images.githubusercontent.com/52409213/223462216-1c2ce791-aaa0-4616-8f96-a35205c9b4ec.png)

**Comment by nicolai-wachenschwan** [comment]
Thank you for testing the code, I got rid of the tuple type hint, would you give it another shot?

I am happy you got it running :)

I never saw this blobs in my models before, can you post your gcode here?
The overall surface seems to have a lot of imperfections, is this usual for your printer or just the lighting of the photo?

**Comment by 18Markus1984** [comment]
The surface looks wired because of Chromatic aberration, this is a photo effect and has nothing to do with the model. Sorry for confusing you. The model surface finish besides the blob in the middle looks good. I can upload the gcode tommorow from my work pc.
![grafik](https://user-images.githubusercontent.com/52409213/223569962-0044171a-1ff0-45cb-8499-ecdfc5cf7f09.png)

**Comment by 18Markus1984** [comment]
We tried a print that would decently fail to test out how much we can go with it. That's petg. What we thought could be useful is a z-hope bevor moving to a different location because we noticed the surface got really pushed.
![grafik](https://user-images.githubusercontent.com/52409213/223664864-ad64871e-c5d8-4ae8-b69a-f78de706532f.png)
![grafik](https://user-images.githubusercontent.com/52409213/223664905-1396b70a-1880-4fdd-89c2-ac65be50af8e.png)

**Comment by nicolai-wachenschwan** [comment]
PLA is already tricky to print in Arcs, but PETG will be much harder, bc of stringing, but also because mechanical strength might depend on the cooling settings. Zhop is currently not supported, as described in limitations section. + it would add to the stringing.

You will need to fiddle a lot with the settings to get it working with petg, but feel free to give it a try!
