### ISSUE TITLE
Layer 0: no height found

### ISSUE THREAD

**Issue by ghylander** [nicolai-wachenschwan/arc-overhang-prusaslicer-integration#62]
Getting this warning when executing the script

Tried to debug it but it's confusing,
I don't know where the script is trying to read the layer height from.

**Comment by nicolai-wachenschwan** [comment]
Hi, it splits the gcode into layers looking for ";LAYER_CHANGE" in the file to split into layers. maybe this keyword is used after the initial config, when the printer starts printing. The height is checked by ";HEIGHT" within each layer. But no need to worry about this warning, it has no influence on other layers.

**Comment by ghylander** [comment]
Perhaps do not show the warning at layer 0 or add context to the warning, ie: `"(can be safely ignored at layer 0)"`
